### ISSUE TITLE
How to apply the mappings to exiting data?

### ISSUE THREAD

**Issue by srikadati** [markharwood/netrisk#1]
Hello,

Thanks for creating this wonderful tool! I was wondering how to apply this mapping and use this plugin for existing data in elasticsearch. I tried to use the commands in the indexanondata.sh script, by replacing the elasticsearch hostname and index name, and replacing remote_host with the column name for my IP address. This just created a new index (with same name), with the new mapping added to it. But it contains no documents. So, now I have 2 indices with same names.
I am still new to this. Could you please give me some pointers on how we could apply this mapping to the existing data. 

For any new data I import I guess I have to create index first and then import data?

Appreciate your help!

Thanks!

**Comment by markharwood** [comment]
Thanks for your feedback and apologies for the delay in responding.

> So, now I have 2 indices with same names.

This shouldn't be possible if they are in the same cluster.

> Could you please give me some pointers on how we could apply this mapping to the existing data.

The mapping used by this tool requires that your indexed content is subjected to a particular formatting when stored in the index. This is defined by the the choice of "analyzer" and it is highly unlikely that any pre-existing index you may have has the correct field name and analyzer mapping that this tool relies on.

You would have to modify the indexanondata.sh script to read in your source of log data and index it into a new index with the correct mapping.
